echo Building \'hblhost-txt-`uname -m`\' ...
gcc -Wall main.cpp -D HBLHOST_TEXTRESPONSEONLY -o hblhost-txt-`uname -m`
echo Building \'hblhost-mp4-`uname -m`\' ...
gcc -Wall main.cpp -o hblhost-mp4-`uname -m`
echo Done!
